### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by marado** [centraldedados/eleicoes-legislativas#1]
Em http://centraldedados.pt/eleicoes-legislativas/ os dados são apresentados não só em CSV nas também em JSON. Seria interessante ter aqui não só o JSON gerado, também, como informação sobre como é que o JSON foi gerado a partir do CSV (o script que o fez, link para ele ou uma descição de como obter aquele JSON a partir daquele CSV).

**Comment by rlafuente** [comment]
Sim, é verdade; o JSON é uma tradução simples do CSV, sem mais acrescentos, como é o caso com quase todos os datasets da Central

**Comment by rlafuente** [comment]
FAQ atualizado pra esclarecer isto
